version: '3.8'

services:

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3002:3000"
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=value_db
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      # Google Sheets configuration
      - DATA_SOURCE=google-sheet
      - GOOGLE_SHEET_ID=1r4Y7tWSdyRc-XIW21b9x8felxgBUDKikglFZTB61o5E
      - GOOGLE_SHEET_NAME=APP
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3001/value"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=value_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.25
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data: 