version: '3.8'

services:
  ui:
    build:
      context: ../ui
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      # Standardized database environment variables
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_HOST=${POSTGRES_HOST:-db}
      - DB_NAME=${POSTGRES_DB:-value_db}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_PORT=${POSTGRES_PORT:-5432}
      # Google Sheets configuration
      - DATA_SOURCE=google-sheet
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_SHEET_NAME=${GOOGLE_SHEET_NAME}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_SPEAKERS_SHEET_NAME=${GOOGLE_SPEAKERS_SHEET_NAME}
      # Email configuration
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM:-"ETHCluj Conference <noreply@ethcluj.org>"}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3001/value"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-value_db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.25
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data:
