# Speaker image positioning overrides
# By default, speaker images are positioned with object-top
# Speakers listed here will have their images positioned with object-center instead

speakerImagePositioning:
  # List of speaker names (case-insensitive) that should have center-focused images
  centerFocused:
    - "George Loukovitis"
    - "Anders Holmbjerg Kristiansen"
    - "Luis"

